# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 12110
  servlet:
    context-path: /whcity

spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
    
logging:
  level: debug
  level.io.dfjx: debug
  path: logs/
  file: admin.log